#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#     "mido>=1.3.3",
# ]
# requires-python = ">=3.14"
# ///
# Copyright (C) 2026 Julian Valentin
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Postprocess MIDI files generated by MuseScore.

The following actions are performed on each MIDI file:

- MuseScore's note velocities are generally too high. This script applies a piecewise linear velocity curve to fix this.
- MuseScore's instrument and track names are generic, especially for four-hand pieces. This script renames left-hand and
  right-hand tracks to "Left hand" and "Right hand". In addition, in detects if the piece is a four-hand piece, in which
  case the respective track names are prefixed with "Primo" and "Secondo".
- Add a metronome track with a regular click on each beat. The time signature changes are detected, and the metronome
  clicks are adjusted accordingly.
"""

import argparse
import logging
from dataclasses import dataclass
from itertools import pairwise
from pathlib import Path
from shutil import copyfile
from statistics import mean
from typing import TYPE_CHECKING

import mido  # type: ignore[import-untyped]

if TYPE_CHECKING:
    from collections.abc import Sequence


@dataclass(frozen=True, kw_only=True)
class MetronomeClick:
    """Metronome click."""

    note: int
    """MIDI note number of the metronome click."""
    velocity: int
    """MIDI velocity of the metronome click."""


MIN_VELOCITY = 0
MAX_VELOCITY = 127
DEFAULT_VELOCITY_CURVE = ((MIN_VELOCITY, 0), (60, 60), (MAX_VELOCITY, 100))

DEFAULT_METRONOME_CLICK = MetronomeClick(note=76, velocity=80)
DEFAULT_METRONOME_DENOMINATORS = (2.0, 4.0, 8.0)

_logger = logging.getLogger(__name__)


def main(string_arguments: Sequence[str] | None = None) -> None:
    """Run main function.

    :param string_arguments: Command line arguments as a list of strings. If ``None``, arguments will be taken from the
        command line.
    """
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    arguments = parse_arguments(string_arguments)
    for input_path in arguments.input_paths:
        process_file(
            input_path,
            arguments.output_dir,
            velocity_curve=arguments.velocity_curve,
            metronome_denominators=arguments.metronome_denominators,
            dry_run=arguments.dry_run,
        )


def parse_arguments(string_arguments: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command line arguments.

    :param string_arguments: Command line arguments as a list of strings. If ``None``, arguments will be taken from the
        command line.
    :return: Parsed arguments.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-d",
        "--metronome-denominators",
        metavar="DENOMINATOR",
        type=float,
        nargs="+",
        default=DEFAULT_METRONOME_DENOMINATORS,
        help="Denominators of the time signatures to use for the metronome tracks (default: %(default)s).",
    )
    parser.add_argument(
        "-n",
        "--dry-run",
        action=argparse.BooleanOptionalAction,
        help="If set, the script will only print the actions it would perform, but not write any files.",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        metavar="DIR",
        type=Path,
        help="Directory to write output MIDI files to. If not given, the input files will be modified in-place, but a "
        "backup copy will be created with the same name and a .bak extension.",
    )
    parser.add_argument(
        "--velocity-curve",
        metavar="X,Y",
        type=lambda s: tuple(map(int, s.split(","))),
        nargs="+",
        default=DEFAULT_VELOCITY_CURVE,
        help="Velocity curve as a list of X,Y pairs. X is the original velocity, and Y is the fixed velocity. The "
        "curve will be applied piecewise linearly between the specified points. X values must be strictly "
        f"monotonically increasing, start with {MIN_VELOCITY}, and end with {MAX_VELOCITY} (default: %(default)s).",
    )
    parser.add_argument(
        "input_paths",
        metavar="PATH",
        type=Path,
        nargs="+",
        help="Path to MIDI files to fix.",
    )
    return parser.parse_args(string_arguments)


def process_file(
    input_path: Path,
    output_dir: Path | None = None,
    *,
    velocity_curve: Sequence[tuple[int, int]] = DEFAULT_VELOCITY_CURVE,
    metronome_denominators: Sequence[float] = DEFAULT_METRONOME_DENOMINATORS,
    dry_run: bool = False,
) -> None:
    """Process a single MIDI file.

    :param input_path: Path to the MIDI file to process.
    :param output_dir: Directory to write the output MIDI file to. If ``None``, the input file will be modified in-place
        (with a backup copy created).
    :param velocity_curve: Velocity curve as a list of *X*,*Y* pairs. *X* is the original velocity, and *Y* is the fixed
        velocity. The curve will be applied piecewise linearly between the specified points. *X* values must be
        strictly monotonically increasing, start with :data:`MIN_VELOCITY`, and end with :data:`MAX_VELOCITY`.
    :param metronome_denominator: Denominator of the time signature to use for the metronome track.
    :param dry_run: If ``True``, the function will only print the actions it would perform.
    """
    if output_dir is None:
        back_up_file(input_path, dry_run=dry_run)
        output_path = input_path
        _logger.info("%s %s in place", "would process" if dry_run else "processing", input_path)
    else:
        output_path = output_dir / input_path.name
        if output_path.resolve() == input_path.resolve():
            msg = "output_dir cannot be the same as the directory of input_path"
            raise ValueError(msg)
        _logger.info(
            "%s %s and %s output to %s",
            "would process" if dry_run else "processing",
            input_path,
            "writing" if not dry_run else "would write",
            output_path,
        )
    midi_file = mido.MidiFile(input_path)
    adjust_velocity(midi_file, velocity_curve=velocity_curve)
    rename_tracks(midi_file)
    add_metronome_tracks(midi_file, denominators=metronome_denominators)
    if not dry_run:
        midi_file.save(output_path)


def back_up_file(input_path: Path, *, dry_run: bool = False) -> None:
    """Create a backup copy of the input file.

    :param input_path: Path to the file to back up.
    :param dry_run: If ``True``, the function will only print the action it would perform.
    """
    output_path = input_path.with_suffix(f".bak{input_path.suffix}")
    counter = 0
    while output_path.exists():
        counter += 1
        output_path = input_path.with_suffix(f".bak{counter}{input_path.suffix}")
    _logger.info("%s backup copy of %s at %s", "creating" if not dry_run else "would create", input_path, output_path)
    if not dry_run:
        copyfile(input_path, output_path)


def adjust_velocity(
    midi_file: mido.MidiFile, velocity_curve: Sequence[tuple[int, int]] = DEFAULT_VELOCITY_CURVE
) -> None:
    """Adjust velocity of MIDI file.

    :param midi_file: MIDI file to adjust.
    :param velocity_curve: Velocity curve as a list of *X*,*Y* pairs. *X* is the original velocity, and *Y* is the fixed
        velocity. The curve will be applied piecewise linearly between the specified points. *X* values must be
        strictly monotonically increasing, start with :data:`MIN_VELOCITY`, and end with :data:`MAX_VELOCITY`.
    """
    if velocity_curve[0][0] != MIN_VELOCITY:
        msg = f"velocity curve must start with X = {MIN_VELOCITY}"
        raise ValueError(msg)
    if velocity_curve[-1][0] != MAX_VELOCITY:
        msg = f"velocity curve must end with X = {MAX_VELOCITY}"
        raise ValueError(msg)
    if any(x1 >= x2 for (x1, _), (x2, _) in pairwise(velocity_curve)):
        msg = "X values of velocity curve must be monotonically increasing"
        raise ValueError(msg)
    for track in midi_file.tracks:
        for message in track:
            if message.type == "note_on":
                for (x1, y1), (x2, y2) in pairwise(velocity_curve):
                    if x1 <= message.velocity <= x2:
                        message.velocity = round(
                            y1 + (y2 - y1) * (message.velocity - x1) / (x2 - x1),
                        )
                        break


def rename_tracks(midi_file: mido.MidiFile) -> None:
    """Rename tracks in the MIDI file.

    If the piece is a four-hand piece, the respective track names are prefixed with "Primo" and "Secondo".
    Otherwise, left-hand and right-hand tracks are renamed to "Left hand" and "Right hand".

    :param midi_file: MIDI file to rename tracks in.
    """
    match len(midi_file.tracks):
        case 1:
            track_names = ["Piano"]
        case 2:
            track_names = ["Left hand", "Right hand"]
        case 4:
            track_names = ["Secondo left hand", "Secondo right hand", "Primo left hand", "Primo right hand"]
        case _:
            _logger.warning("only MIDI files with 1, 2, or 4 tracks are supported, got: %d", len(midi_file.tracks))
            return
    for track, track_name in zip(sorted(midi_file.tracks, key=compute_mean_note), track_names, strict=True):
        rename_track(track, track_name)


def compute_mean_note(track: mido.MidiTrack) -> float:
    """Compute the mean note of a MIDI track.

    :param track: Track to compute the mean note of.
    :return: Mean note of the track.
    """
    return mean(float(message.note) for message in track if message.type == "note_on")


def rename_track(track: mido.MidiTrack, new_name: str) -> None:
    """Rename a MIDI track.

    :param track: Track to rename.
    :param new_name: New name for the track.
    """
    for message in track:
        if message.type == "track_name":
            message.name = new_name
            return
    track.insert(0, mido.MetaMessage("track_name", name=new_name))


@dataclass(frozen=True, kw_only=True)
class MessageWithAbsoluteTime:
    """MIDI message with absolute time."""

    message: mido.Message
    """MIDI message."""
    absolute_time: int
    """Absolute time of the message in ticks."""


def add_metronome_tracks(
    midi_file: mido.MidiFile,
    *,
    denominators: Sequence[float] = DEFAULT_METRONOME_DENOMINATORS,
    click: MetronomeClick | None = None,
) -> None:
    """Add metronome tracks to the MIDI file.

    :param midi_file: MIDI file to add the metronome track to.
    :param denominators: Denominators of the time signatures to use for the metronome tracks.
    :param click: Metronome click to use.
    """
    if not click:
        click = DEFAULT_METRONOME_CLICK
    change_times = get_signature_change_times(midi_file)
    for idx, denominator in enumerate(denominators):
        messages = get_metronome_messages(
            midi_file, change_times, denominator=denominator, channel=idx + 2, click=click
        )
        metronome = mido.MidiTrack()
        metronome.append(mido.MetaMessage("track_name", name=f"Metronome (1/{denominator:g})", time=0))
        for previous, current in pairwise([messages[0], *messages]):
            current.message.time = current.absolute_time - previous.absolute_time
            metronome.append(current.message)
        midi_file.tracks.append(metronome)


def get_signature_change_times(midi_file: mido.MidiFile) -> list[int]:
    """Get time signature change times from a MIDI file.

    :param midi_file: MIDI file to get time signature change times from.
    :return: List of time signature change times.
    """
    change_times = []
    for track in midi_file.tracks:
        time = 0
        for message in track:
            time += message.time
            if message.type == "time_signature":
                change_times.append(time)
        if change_times:
            break
    return change_times or [0]


def get_metronome_messages(
    midi_file: mido.MidiFile,
    change_times: Sequence[int],
    *,
    denominator: float,
    channel: int,
    click: MetronomeClick | None = None,
) -> list[MessageWithAbsoluteTime]:
    """Get MIDI messages for the metronome track.

    :param midi_file: MIDI file to get the metronome messages for.
    :param change_times: Time signature change times in the MIDI file.
    :param denominator: Denominator of the time signature to use for the metronome track.
    :param channel: MIDI channel to use for the metronome track.
    :param click: Metronome click to use.
    :return: List of MIDI messages for the metronome track, sorted by absolute time.
    """
    if not click:
        click = DEFAULT_METRONOME_CLICK
    duration = max([sum(m.time for m in track) for track in midi_file.tracks])
    messages = []
    for start_time, end_time in pairwise([*change_times, duration + 1]):
        ticks_per_beat = midi_file.ticks_per_beat * 4 / denominator
        click_duration = round(ticks_per_beat / 16)
        time = start_time
        while time < end_time:
            messages.append(
                MessageWithAbsoluteTime(
                    message=mido.Message("note_on", note=click.note, velocity=click.velocity, channel=channel, time=0),
                    absolute_time=time,
                )
            )
            messages.append(
                MessageWithAbsoluteTime(
                    message=mido.Message("note_off", note=click.note, velocity=0, channel=channel, time=0),
                    absolute_time=time + click_duration,
                )
            )
            time += round(ticks_per_beat)
    messages.sort(key=lambda m: (m.absolute_time, 0 if m.message.type == "note_off" else 1))
    return messages


if __name__ == "__main__":
    main()
