# Copyright (C) 2026 Julian Valentin
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install uv
        uses: astral-sh/setup-uv@v7.6.0
      - name: check formatting with Ruff
        run: uv run ruff format --diff
      - name: lint with Ruff
        run: uv run ruff check
      - name: lint with mypy and ty
        run: |
          for SCRIPT in src/*.py
          do
            echo
            echo "linting $SCRIPT"
            uv sync --script "$SCRIPT"
            SCRIPT_PYTHON="$(uv python find --script "$SCRIPT")"
            SCRIPT_SITE_PACKAGES="$("$SCRIPT_PYTHON" -c '
              import site
              print(next(p for p in site.getsitepackages() if "site-packages" in p))
            ')"
            echo "using site-packages: $SCRIPT_SITE_PACKAGES"
            echo
            echo "running mypy on $SCRIPT"
            PYTHONPATH="$SCRIPT_SITE_PACKAGES" uv run mypy "$SCRIPT"
            echo
            echo "running ty on $SCRIPT"
            PYTHONPATH="$SCRIPT_SITE_PACKAGES" uv run ty check "$SCRIPT"
          done
